<a href="https://colab.research.google.com/github/funnnkey/Data-Visualisation-project/blob/colab.project/Predictive%20Model%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/bike_sales.txt')

In [ ]:
df['Profit'] = df['Profit'].str.replace('$', '', regex=False)
df['Profit'] = df['Profit'].str.replace(' ', '', regex=False)
df['Profit'] = df['Profit'].str.replace(',', '', regex=False)

In [ ]:
df['Cost'] = df['Cost'].str.replace('$', '', regex=False)
df['Cost'] = df['Cost'].str.replace(' ', '', regex=False)
df['Cost'] = df['Cost'].str.replace(',', '', regex=False)

In [ ]:
df['Profit'] = pd.to_numeric(df['Profit'])
df['Cost'] = pd.to_numeric(df['Cost'])

In [ ]:
df.head()

,Year,Customer_Age,Order_Quantity,Profit,Cost,Age_Group_Young Adults (25-34),Age_Group_Youth (<25),Customer_Gender_M,Country_Germany,Country_United Kingdom,...,"Revenue _ $1,264.00","Revenue _ $1,480.00","Revenue _ $2,003.00","Revenue _ $2,125.00","Revenue _ $2,218.00","Revenue _ $2,227.00","Revenue _ $2,272.00","Revenue _ $3,435.00",Revenue _ $529.00,"Revenue _ $8,996.00"
0,2021,39,4,3988.0,5008.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,2021,42,3,232.0,1032.0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
2,2021,36,2,792.0,1426.0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
3,2021,20,1,717.0,1555.0,0,1,1,1,0,...,0,0,0,0,0,0,1,0,0,0
4,2021,23,1,1264.0,2171.0,0,1,1,0,1,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
df.tail()

,Year,Customer_Age,Order_Quantity,Profit,Cost,Age_Group_Young Adults (25-34),Age_Group_Youth (<25),Customer_Gender_M,Country_Germany,Country_United Kingdom,...,"Revenue _ $1,264.00","Revenue _ $1,480.00","Revenue _ $2,003.00","Revenue _ $2,125.00","Revenue _ $2,218.00","Revenue _ $2,227.00","Revenue _ $2,272.00","Revenue _ $3,435.00",Revenue _ $529.00,"Revenue _ $8,996.00"
6,2021,28,1,570.0,1555.0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
7,2021,28,1,185.0,344.0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
8,2021,31,1,448.0,1555.0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
9,2021,34,1,397.0,1083.0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
10,2021,44,1,961.0,1266.0,0,0,1,0,1,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11 entries, 0 to 10
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Year                            11 non-null     int64
 1   Customer_Age                    11 non-null     int64
 2   Order_Quantity                  11 non-null     int64
 3   Profit                          11 non-null     float64
 4   Cost                            11 non-null     float64
 5   Age_Group_Young Adults (25-34)  11 non-null     uint8
 6   Age_Group_Youth (<25)           11 non-null     uint8
 7   Customer_Gender_M               11 non-null     uint8
 8   Country_Germany                 11 non-null     uint8
 9   Country_United Kingdom          11 non-null     uint8
 10  Country_United States           11 non-null     uint8
 11  State_California                11 non-null     uint8
 12  State_England                   11 non-null     uint8
 13  State_Hamburg                   11 non-null     uint8
 14  State_New South Wales           11 non-null     uint8
 15  State_South Australia           11 non-null     uint8
 16  State_Washington                11 non-null     uint8
 17   Revenue _ $1,264.00            11 non-null     uint8
 18   Revenue _ $1,480.00            11 non-null     uint8
 19   Revenue _ $2,003.00            11 non-null     uint8
 20   Revenue _ $2,125.00            11 non-null     uint8
 21   Revenue _ $2,218.00            11 non-null     uint8
 22   Revenue _ $2,227.00            11 non-null     uint8
 23   Revenue _ $2,272.00            11 non-null     uint8
 24   Revenue _ $3,435.00            11 non-null     uint8
 25   Revenue _ $529.00              11 non-null     uint8
 26   Revenue _ $8,996.00            11 non-null     uint8
dtypes: float64(2), int64(3), uint8(22)
memory usage: 770.0 bytes

In [ ]:
df.describe()

,Year,Customer_Age,Order_Quantity,Profit,Cost,Age_Group_Young Adults (25-34),Age_Group_Youth (<25),Customer_Gender_M,Country_Germany,Country_United Kingdom,...,"Revenue _ $1,264.00","Revenue _ $1,480.00","Revenue _ $2,003.00","Revenue _ $2,125.00","Revenue _ $2,218.00","Revenue _ $2,227.00","Revenue _ $2,272.00","Revenue _ $3,435.00",Revenue _ $529.00,"Revenue _ $8,996.00"
count,11.0,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,...,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
mean,2021.0,31.636364,1.545455,903.545455,1609.818182,0.363636,0.272727,0.454545,0.181818,0.181818,...,0.090909,0.090909,0.090909,0.090909,0.090909,0.090909,0.090909,0.090909,0.090909,0.090909
std,0.0,8.065640,1.035725,1072.653846,1226.440771,0.504525,0.467099,0.522233,0.404520,0.404520,...,0.301511,0.301511,0.301511,0.301511,0.301511,0.301511,0.301511,0.301511,0.301511,0.301511
min,2021.0,20.000000,1.000000,185.000000,344.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2021.0,25.500000,1.000000,391.000000,1057.500000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2021.0,31.000000,1.000000,570.000000,1426.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2021.0,37.500000,1.500000,876.500000,1555.000000,1.000000,0.500000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2021.0,44.000000,4.000000,3988.000000,5008.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df.describe(include='all')

,Year,Customer_Age,Order_Quantity,Profit,Cost,Age_Group_Young Adults (25-34),Age_Group_Youth (<25),Customer_Gender_M,Country_Germany,Country_United Kingdom,...,"Revenue _ $1,264.00","Revenue _ $1,480.00","Revenue _ $2,003.00","Revenue _ $2,125.00","Revenue _ $2,218.00","Revenue _ $2,227.00","Revenue _ $2,272.00","Revenue _ $3,435.00",Revenue _ $529.00,"Revenue _ $8,996.00"
count,11.0,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,...,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
mean,2021.0,31.636364,1.545455,903.545455,1609.818182,0.363636,0.272727,0.454545,0.181818,0.181818,...,0.090909,0.090909,0.090909,0.090909,0.090909,0.090909,0.090909,0.090909,0.090909,0.090909
std,0.0,8.065640,1.035725,1072.653846,1226.440771,0.504525,0.467099,0.522233,0.404520,0.404520,...,0.301511,0.301511,0.301511,0.301511,0.301511,0.301511,0.301511,0.301511,0.301511,0.301511
min,2021.0,20.000000,1.000000,185.000000,344.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2021.0,25.500000,1.000000,391.000000,1057.500000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2021.0,31.000000,1.000000,570.000000,1426.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2021.0,37.500000,1.500000,876.500000,1555.000000,1.000000,0.500000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2021.0,44.000000,4.000000,3988.000000,5008.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df.shape

(11, 27)

In [ ]:
df.columns

Index(['Year', 'Customer_Age', 'Order_Quantity', 'Profit', 'Cost',
       'Age_Group_Young Adults (25-34)', 'Age_Group_Youth (<25)',
       'Customer_Gender_M', 'Country_Germany', 'Country_United Kingdom',
       'Country_United States', 'State_California', 'State_England',
       'State_Hamburg', 'State_New South Wales', 'State_South Australia',
       'State_Washington', ' Revenue _ $1,264.00 ', ' Revenue _ $1,480.00 ',
       ' Revenue _ $2,003.00 ', ' Revenue _ $2,125.00 ',
       ' Revenue _ $2,218.00 ', ' Revenue _ $2,227.00 ',
       ' Revenue _ $2,272.00 ', ' Revenue _ $3,435.00 ', ' Revenue _ $529.00 ',
       ' Revenue _ $8,996.00 '],
      dtype='object')

In [ ]:
df['Profit']

0     3988.0
1      232.0
2      792.0
3      717.0
4     1264.0
5      385.0
6      570.0
7      185.0
8      448.0
9      397.0
10     961.0
Name: Profit, dtype: float64

In [ ]:
df['Profit'].value_counts()

3988.0    1
232.0     1
792.0     1
717.0     1
1264.0    1
385.0     1
570.0     1
185.0     1
448.0     1
397.0     1
961.0     1
Name: Profit, dtype: int64

In [ ]:
df.isna().sum()

Year                              0
Customer_Age                      0
Order_Quantity                    0
Profit                            0
Cost                              0
Age_Group_Young Adults (25-34)    0
Age_Group_Youth (<25)             0
Customer_Gender_M                 0
Country_Germany                   0
Country_United Kingdom            0
Country_United States             0
State_California                  0
State_England                     0
State_Hamburg                     0
State_New South Wales             0
State_South Australia             0
State_Washington                  0
 Revenue _ $1,264.00              0
 Revenue _ $1,480.00              0
 Revenue _ $2,003.00              0
 Revenue _ $2,125.00              0
 Revenue _ $2,218.00              0
 Revenue _ $2,227.00              0
 Revenue _ $2,272.00              0
 Revenue _ $3,435.00              0
 Revenue _ $529.00                0
 Revenue _ $8,996.00              0
dtype: int64

In [ ]:
df.isnull().sum()

Year                              0
Customer_Age                      0
Order_Quantity                    0
Profit                            0
Cost                              0
Age_Group_Young Adults (25-34)    0
Age_Group_Youth (<25)             0
Customer_Gender_M                 0
Country_Germany                   0
Country_United Kingdom            0
Country_United States             0
State_California                  0
State_England                     0
State_Hamburg                     0
State_New South Wales             0
State_South Australia             0
State_Washington                  0
 Revenue _ $1,264.00              0
 Revenue _ $1,480.00              0
 Revenue _ $2,003.00              0
 Revenue _ $2,125.00              0
 Revenue _ $2,218.00              0
 Revenue _ $2,227.00              0
 Revenue _ $2,272.00              0
 Revenue _ $3,435.00              0
 Revenue _ $529.00                0
 Revenue _ $8,996.00              0
dtype: int64

In [ ]:
y = df['Profit']
x = df[['Cost']]

In [ ]:
df.shape

(11, 27)

In [ ]:
x.shape

(11, 1)

In [ ]:
y.shape

(11,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(x,y,train_size= 0.7,random_state=2529)
X_train

      Cost
6   1555.0
8   1555.0
10  1266.0
7    344.0
4   2171.0
2   1426.0
0   5008.0

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(x,y,train_size= 0.7,random_state=2529)
y_train

6      570.0
8      448.0
10     961.0
7      185.0
4     1264.0
2      792.0
0     3988.0
Name: Profit, dtype: float64

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((7, 1), (4, 1), (7,), (4,))

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

-448.1214908915035

In [ ]:
model.coef_

array([0.85139591])

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_test

5    385.0
3    717.0
9    397.0
1    232.0
Name: Profit, dtype: float64

In [ ]:
y_pred

array([158.92378949, 875.79914163, 473.9402744 , 430.51908323])

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,y_pred)

0.46454451064655505